version: '3.1'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: tredmor
      POSTGRES_USER: tredmor
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    external: true